<a href="https://colab.research.google.com/github/Emmanuel-dev-oss/Python/blob/main/Abidoye_Emmanuel_Oluwadamilare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#String Manipulation

"""Convert A String To Lowercase"""
text = "HELLO WORLD"
lowercase_text = text.lower()
print(f"Original text: {text}")
print(f"Lowercase text: {lowercase_text}")
print("                      ")


"""Convert A String To Uppercase"""
text = "hello world"
uppercase_text = text.upper()
print(f"Original text: {text}")
print(f"Uppercase text: {uppercase_text}")
print("                      ")


"""String Replacement"""
text = "I'm An Approved Developer"
new_text = text.replace("Approved", "Unique")
print(f"Original text: {text}")
print(f"New text: {new_text}")
print("                      ")


"""String Counting"""
text = "I'm An Approved Developer"
count = text.count("o")
print(f"Original text: {text}")
print(f"Count of o: {count}")
print("                      ")


"""String Spliting"""
text = "I'm An Approved Developer"
words = text.split()
print(f"Original text: {text}")
print(f"Words: {words}")
print("                      ")

"""String Stemming and Lemmatization"""
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet')
text = "Running with little children makes sadness disappear"
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stemmed_words = [stemmer.stem(word) for word in text.split()]
lemmatized_words = [lemmatizer.lemmatize(word) for word in text.split()]
print(f"Original text: {text}")
print(f"Stemmed words: {stemmed_words}")
print(f"Lemmatized words: {lemmatized_words}")

Original text: HELLO WORLD
Lowercase text: hello world

Original text: hello world
Uppercase text: HELLO WORLD

Original text: I'm An Approved Developer
New text: I'm An Unique Developer

Original text: I'm An Approved Developer
Count of o: 2

Original text: I'm An Approved Developer
Words: ["I'm", 'An', 'Approved', 'Developer']

Original text: Running with little children makes sadness disappear
Stemmed words: ['run', 'with', 'littl', 'children', 'make', 'sad', 'disappear']
Lemmatized words: ['Running', 'with', 'little', 'child', 'make', 'sadness', 'disappear']

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


#Secure Banking System Pseudocode

##Variables
- `account_number`: unique account identifier
- `pin`: 4-digit personal identification number
- `balance`: current account balance
- `transaction_history`: record of all transactions

Main Program
*Initialize Account*
1. Set `account_number` to a unique value
2. Set `pin` to a secure value
3. Set `balance` to 0
4. Initialize `transaction_history` as an empty list

Display Menu
1. Print "Welcome to Secure Banking!"
2. Print "Please select an option:"
3. Print "1. Deposit"
4. Print "2. Withdraw"
5. Print "3. Check Balance"
6. Print "4. Transaction History"
7. Print "5. Exit"

Get User Input
1. Ask user to take their choice of action (1, 2, 3, 4, or 5)

Process User Input

*Deposit*

1. Ask user to enter amount to deposit
2. Verify user's identity using `pin`
3. Add amount to `balance`
4. Append transaction to `transaction_history`
5. Print "Deposit successful!"


*Withdraw*

1. Ask user to enter amount to withdraw
2. Verify user's identity using `pin`
3. Check if `balance` is sufficient
4. If sufficient, subtract amount from `balance`
5. Append transaction to `transaction_history`
6. Print "Withdrawal successful!"

*Check Balance*

1. Verify user's identity using `pin`
2. Print "Your current balance is: " + `balance`

*Transaction History*

1. Verify user's identity using `pin`
2. Print `transaction_history`


*Exit*

1. Print "Thank you for using Secure Banking!"
2. Exit program

Error Handling
*Invalid Input*

1. If user enters an invalid choice (not 1, 2, 3, 4, or 5)
2. Print "Invalid choice. Please try again."

*Invalid PIN*

1. If user enters incorrect `pin`
2. Print "Invalid PIN. Please try again."

*Insufficient Balance*

1. If user tries to withdraw more than their

current balance
2. Print "Insufficient balance. Please try again."

In [ ]:
import pandas as pd
biodata = [['Ade Bayo', 'Male', 19, 'Nigeria', 'Data Analysis', 'Single', '08134572367'],
           ['Emmanuel Abidoye', 'Male', 20, 'Nigeria', 'Software Developer', 'Single', '08162807117'],
           ['Joan Druke', 'Male', 21, 'Carlifonia', 'Graphics Designer', 'Single', '+2348015678910'],
           ['Yui Nakamura', 'Female', 32, 'Japanese', 'Software Engineer', 'Married', '+819012345678'],
           ['Lucas Silva', 'Male', 29, 'Brazilian', 'Data Manager', 'Single', '+552198765432'],
           ['Rohan Patel', 'Male', 41, 'Indian', 'Enterprnuer(E-commerce)', 'Married', '+919876543210'],
           ['Nandi Mthembu', 'Female', 35, 'South African', 'Journalist', 'Divorced', '+27821234567'],
           ['Mei-Ling Wong', 'Female', 28, 'Chinese', 'Data Scientist', 'Single', '+861301234567'],
           ['Emily Wilson', 'Female', 39, 'Australian', 'Game Developer', 'Single', '+6141234567'],
           ['Amr Hassan', 'Male', 45, 'Egyptian', 'Archaelogist', 'Married', '+201012345678']]
df = pd.DataFrame(biodata, columns=['Name', 'Gender', 'Age', 'Nationality', 'Career', 'Marital Status', 'Contact'])
df

,Name,Gender,Age,Nationality,Career,Marital Status,Contact
0,Ade Bayo,Male,19,Nigeria,Data Analysis,Single,08134572367
1,Emmanuel Abidoye,Male,20,Nigeria,Software Developer,Single,08162807117
2,Joan Druke,Male,21,Carlifonia,Graphics Designer,Single,+2348015678910
3,Yui Nakamura,Female,32,Japanese,Software Engineer,Married,+819012345678
4,Lucas Silva,Male,29,Brazilian,Data Manager,Single,+552198765432
5,Rohan Patel,Male,41,Indian,Enterprnuer(E-commerce),Married,+919876543210
6,Nandi Mthembu,Female,35,South African,Journalist,Divorced,+27821234567
7,Mei-Ling Wong,Female,28,Chinese,Data Scientist,Single,+861301234567
8,Emily Wilson,Female,39,Australian,Game Developer,Single,+6141234567
9,Amr Hassan,Male,45,Egyptian,Archaelogist,Married,+201012345678